# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

CONFIG += debug \
          warn_on \
          qt \
          thread \
          x11 
TEMPLATE = subdirs 
SUBDIRS += src 
